### ISSUE TITLE
Node version requirement

### ISSUE THREAD

**Issue by bodograumann** [hariseldon78/ts-ast-to-neo4j#1]
I was trying to use this tool according to this article: https://graphaware.com/neo4j/2019/03/09/graph-assisted-typescript-refactoring.html, but turns out it `flatMap` is only available since node.js version 11.0.

**Comment by hariseldon78** [comment]
thanks for noticing. i should be able to replace it with the flatmap function from lodash, i’ll try that in the next days

**Comment by hariseldon78** [comment]
Sorry, i never addressed this issue, but since nodejs has grown quite a bit i think it's not worth the effort.
